# Generated by Django 5.2.15 on 2026-08-09 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0015_variant_option_info'),
        ('customer', '0004_normalize_customer_phones'),
        ('inventory', '0006_inventory_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaymentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fa_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=30, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shop_order_payment_channel',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fa_name', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shop_order_payment_method',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fa_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'shop_order_status',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_info', models.JSONField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reservation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customer.customer')),
            ],
            options={
                'db_table': 'shop_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_type', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variant_info', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.inventorystrategy')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariants')),
            ],
            options={
                'db_table': 'shop_order_item',
            },
        ),
        migrations.CreateModel(
            name='OrderItemReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_type', models.CharField(max_length=32)),
                ('inventory_id', models.BigIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='order.orderitem')),
            ],
            options={
                'db_table': 'shop_order_item_reservation',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('ref_number', models.CharField(blank=True, max_length=128, null=True)),
                ('resource_account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order')),
                ('payment_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='order.orderpaymentchannel')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order.orderpaymentmethod')),
            ],
            options={
                'db_table': 'shop_order_payment',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='successful_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_order', to='order.orderpayment'),
        ),
        migrations.CreateModel(
            name='OrderPaymentChannelSupportMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_methods', to='order.orderpaymentchannel')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_channels', to='order.orderpaymentmethod')),
            ],
            options={
                'db_table': 'shop_order_payment_channel_support',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.orderstatus'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='shop_order_item_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='shop_order_item_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='orderitemreservation',
            index=models.Index(fields=['inventory_type', 'inventory_id'], name='shop_ord_resrv_invtry_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderpaymentchannelsupportmethod',
            constraint=models.UniqueConstraint(fields=('payment_channel', 'payment_method'), name='shop_payment_channel_support_unique'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['order'], name='shop_order_payment_order_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='shop_ord_customer_creat_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'reservation_expires_at'], name='shop_ord_status_resrv_idx'),
        ),
    ]
