# Generated by Django 5.2.15 on 2026-08-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='user_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
