# Generated by Django 5.2.15 on 2026-08-22 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_normalize_customer_phones'),
        ('order', '0008_orderhistory_user_id_orderhistory_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=16)),
                ('reason', models.TextField()),
                ('customer_note', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='customer.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='order.order')),
            ],
            options={
                'db_table': 'shop_return_request',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_request_items', to='order.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.returnrequest')),
            ],
            options={
                'db_table': 'shop_return_request_item',
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['customer', '-requested_at'], name='shop_ret_customer_req_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order', 'status'], name='shop_ret_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['order_item'], name='shop_ret_item_order_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='shop_return_item_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='returnrequestitem',
            constraint=models.UniqueConstraint(fields=('return_request', 'order_item'), name='shop_return_unique_order_item'),
        ),
    ]
