# Generated by Django 5.2.15 on 2026-09-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_inventorytransfer'),
        ('order', '0013_order_shipping_original_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemreservation',
            name='linked_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_reservations', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='orderitemreservation',
            name='linked_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_reservations', to='inventory.inventoryunit'),
        ),
        migrations.AddIndex(
            model_name='orderitemreservation',
            index=models.Index(fields=['linked_inventory'], name='shop_ord_resrv_new_inv_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitemreservation',
            index=models.Index(fields=['linked_unit'], name='shop_ord_resrv_new_unit_idx'),
        ),
    ]
