from django.urls import path

from .views import (
    AdminCategoryOptionList,
    AdminCategorySEO,
    AdminBrandSEO,
    AdminContentComponentContractList,
    AdminLandingPageDetail,
    AdminLandingPageList,
    AdminLandingPagePublish,
    AdminLandingPageSEO,
    AdminPageDetail,
    AdminPageList,
    AdminPagePublish,
    AdminPageSEO,
    AdminProductOptionList,
    AdminProductSEO,
    LandingPagePreview,
    PagePreview,
    PublicHomePage,
    PublicLandingPage,
    PublicPage,
    PublicResourceSEO,
    VendorCategoryOptionList,
    VendorComponentContractList,
    VendorLandingPageDetail,
    VendorLandingPageList,
    VendorLandingPagePreview,
    VendorLandingPagePublish,
    VendorLandingPageSEO,
    VendorPageDetail,
    VendorPageList,
    VendorPagePreview,
    VendorPagePublish,
    VendorPageSEO,
    VendorProductOptionList,
)

urlpatterns = [
    path("home", PublicHomePage.as_view()),
    path("admin/landing-pages", AdminLandingPageList.as_view()),
    path("admin/landing-pages/<int:landing_page_id>", AdminLandingPageDetail.as_view()),
    path("admin/landing-pages/<int:landing_page_id>/publish", AdminLandingPagePublish.as_view()),
    path("admin/landing-pages/<int:resource_id>/seo", AdminLandingPageSEO.as_view()),
    path("admin/pages", AdminPageList.as_view()),
    path("admin/pages/<int:page_id>", AdminPageDetail.as_view()),
    path("admin/pages/<int:page_id>/publish", AdminPagePublish.as_view()),
    path("admin/pages/<int:resource_id>/seo", AdminPageSEO.as_view()),
    path("admin/products/<int:resource_id>/seo", AdminProductSEO.as_view()),
    path("admin/categories/<int:resource_id>/seo", AdminCategorySEO.as_view()),
    path("admin/brands/<int:resource_id>/seo", AdminBrandSEO.as_view()),
    path("admin/component-contracts", AdminContentComponentContractList.as_view()),
    path("admin/options/products", AdminProductOptionList.as_view()),
    path("admin/options/categories", AdminCategoryOptionList.as_view()),
    path("vendor/landing-pages", VendorLandingPageList.as_view()),
    path(
        "vendor/landing-pages/<int:resource_id>",
        VendorLandingPageDetail.as_view(),
    ),
    path(
        "vendor/landing-pages/<int:resource_id>/publish",
        VendorLandingPagePublish.as_view(),
    ),
    path(
        "vendor/landing-pages/<int:resource_id>/preview",
        VendorLandingPagePreview.as_view(),
    ),
    path(
        "vendor/landing-pages/<int:resource_id>/seo",
        VendorLandingPageSEO.as_view(),
    ),
    path("vendor/pages", VendorPageList.as_view()),
    path("vendor/pages/<int:resource_id>", VendorPageDetail.as_view()),
    path("vendor/pages/<int:resource_id>/publish", VendorPagePublish.as_view()),
    path("vendor/pages/<int:resource_id>/preview", VendorPagePreview.as_view()),
    path("vendor/pages/<int:resource_id>/seo", VendorPageSEO.as_view()),
    path("vendor/options/products", VendorProductOptionList.as_view()),
    path("vendor/options/categories", VendorCategoryOptionList.as_view()),
    path("vendor/component-contracts", VendorComponentContractList.as_view()),
    path("landing-pages/<str:slug>/preview", LandingPagePreview.as_view()),
    path("landing-pages/<str:slug>", PublicLandingPage.as_view()),
    path("pages/<str:slug>/preview", PagePreview.as_view()),
    path("pages/<str:slug>", PublicPage.as_view()),
    path("seo/<str:resource_type>/<str:slug>", PublicResourceSEO.as_view()),
]
