from django.urls import path

from .views import (
    AdminCategoryOptionList,
    AdminContentComponentContractList,
    AdminLandingPageDetail,
    AdminLandingPageList,
    AdminLandingPagePublish,
    AdminLandingPageSEO,
    AdminPageDetail,
    AdminPageList,
    AdminPagePublish,
    AdminPageSEO,
    AdminProductOptionList,
    AdminProductSEO,
    LandingPagePreview,
    PagePreview,
    PublicHomePage,
    PublicLandingPage,
    PublicPage,
)

urlpatterns = [
    path("home", PublicHomePage.as_view()),
    path("admin/landing-pages", AdminLandingPageList.as_view()),
    path("admin/landing-pages/<int:landing_page_id>", AdminLandingPageDetail.as_view()),
    path("admin/landing-pages/<int:landing_page_id>/publish", AdminLandingPagePublish.as_view()),
    path("admin/landing-pages/<int:resource_id>/seo", AdminLandingPageSEO.as_view()),
    path("admin/pages", AdminPageList.as_view()),
    path("admin/pages/<int:page_id>", AdminPageDetail.as_view()),
    path("admin/pages/<int:page_id>/publish", AdminPagePublish.as_view()),
    path("admin/pages/<int:resource_id>/seo", AdminPageSEO.as_view()),
    path("admin/products/<int:resource_id>/seo", AdminProductSEO.as_view()),
    path("admin/component-contracts", AdminContentComponentContractList.as_view()),
    path("admin/options/products", AdminProductOptionList.as_view()),
    path("admin/options/categories", AdminCategoryOptionList.as_view()),
    path("landing-pages/<str:slug>/preview", LandingPagePreview.as_view()),
    path("landing-pages/<str:slug>", PublicLandingPage.as_view()),
    path("pages/<str:slug>/preview", PagePreview.as_view()),
    path("pages/<str:slug>", PublicPage.as_view()),
]
