# Generated by Django 5.2.15 on 2026-07-23 12:40

import domains.customer.models.customer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', domains.customer.models.customer.CustomerManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_login_at',
            field=models.DateTimeField(blank=True, db_column='last_login_at', null=True),
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_login_at',
            new_name='last_login',
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
