# Generated by Django 5.2.15 on 2026-07-24 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('location', '0002_add_fa_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'inventory_warehouse_status',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('phone_numbers', models.JSONField(blank=True, default=list)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='location.city')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='inventory.warehousestatus')),
            ],
            options={
                'db_table': 'inventory_warehouse',
            },
        ),
    ]
