# Generated by Django 5.2.15 on 2026-07-24 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0002_warehousestatus_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerializedStockStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'inventory_serialized_stock_status',
            },
        ),
        migrations.CreateModel(
            name='SerializedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('sellable', models.BooleanField(default=True)),
                ('reserved', models.BooleanField(default=False)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_stocks', to='catalog.productvariants')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_stocks', to='inventory.warehouse')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_stocks', to='inventory.serializedstockstatus')),
            ],
            options={
                'db_table': 'inventory_serialized_stock',
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sellable', models.PositiveIntegerField()),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('min_stock', models.PositiveIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_stocks', to='catalog.productvariants')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_warehouse_stock',
                'unique_together': {('variant', 'warehouse')},
            },
        ),
    ]
