# Generated by Django 5.2.15 on 2026-07-28 20:09

import django.db.models.functions.text
from django.db import migrations, models
import re


def prepare_inventory_data(apps, schema_editor):
    InventoryStrategy = apps.get_model("inventory", "InventoryStrategy")
    SerializedStock = apps.get_model("inventory", "SerializedStock")
    SerializedStockStatus = apps.get_model("inventory", "SerializedStockStatus")
    Warehouse = apps.get_model("inventory", "Warehouse")
    WarehouseStock = apps.get_model("inventory", "WarehouseStock")

    InventoryStrategy.objects.update_or_create(
        code="normal",
        defaults={"name": "Normal", "description": "Aggregate quantity stock."},
    )
    InventoryStrategy.objects.update_or_create(
        code="serialized",
        defaults={"name": "Serialized", "description": "Individually serialized stock."},
    )

    aliases = {
        "in stock": "in_stock",
        "instock": "in_stock",
        "in_stock": "in_stock",
        "sold": "sold",
        "returned": "returned",
        "damaged": "damaged",
        "lost": "lost",
    }
    used_codes = set()
    for status in SerializedStockStatus.objects.order_by("id"):
        normalized_name = " ".join(status.name.strip().lower().replace("-", " ").split())
        base = aliases.get(normalized_name) or re.sub(r"[^a-z0-9]+", "_", normalized_name).strip("_")
        base = (base or f"status_{status.id}")[:50]
        code = base
        counter = 2
        while code in used_codes:
            suffix = f"_{counter}"
            code = f"{base[:50 - len(suffix)]}{suffix}"
            counter += 1
        status.code = code
        status.save(update_fields=["code"])
        used_codes.add(status.code)
    if "in_stock" not in used_codes:
        SerializedStockStatus.objects.create(code="in_stock", name="in_stock")

    default_ids = list(
        Warehouse.objects.filter(is_default=True).order_by("id").values_list("id", flat=True)
    )
    if len(default_ids) > 1:
        Warehouse.objects.filter(id__in=default_ids[1:]).update(is_default=False)

    for stock in WarehouseStock.objects.all():
        sellable = min(stock.sellable, stock.quantity)
        reserved = min(stock.reserved, sellable)
        if sellable != stock.sellable or reserved != stock.reserved:
            stock.sellable = sellable
            stock.reserved = reserved
            stock.save(update_fields=["sellable", "reserved"])

    used_serials = set()
    for row in SerializedStock.objects.order_by("id"):
        serial_number = " ".join(row.serial_number.split())
        candidate = serial_number
        suffix = f"-{row.id}"
        while candidate.lower() in used_serials:
            candidate = f"{serial_number[:100 - len(suffix)]}{suffix}"
            suffix += "x"
        row.serial_number = candidate
        row.save(update_fields=["serial_number"])
        used_serials.add(candidate.lower())


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_categoryvariantattribute_productvariantselection_and_more'),
        ('inventory', '0004_ensure_normal_inventory_strategy'),
        ('location', '0002_add_fa_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='serializedstockstatus',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(prepare_inventory_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='serializedstockstatus',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='serializedstock',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='serializedstock',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('serial_number'), name='inventory_serial_number_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='inventory_single_default_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='warehousestock',
            constraint=models.CheckConstraint(condition=models.Q(('sellable__lte', models.F('quantity'))), name='inventory_stock_sellable_lte_quantity'),
        ),
        migrations.AddConstraint(
            model_name='warehousestock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('sellable'))), name='inventory_stock_reserved_lte_sellable'),
        ),
    ]
