# Generated by Django 5.2.15 on 2026-08-26 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_brand_categories'),
        ('inventory', '0006_inventory_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_buy_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('supplied_at', models.DateTimeField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_supplies', to='catalog.productvariants')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_supplies', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_supply',
                'ordering': ['supplied_at', 'id'],
                'indexes': [models.Index(fields=['variant', 'warehouse', 'supplied_at'], name='inv_supply_variant_wh_supplied')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_supply_quantity_gt_zero'), models.CheckConstraint(condition=models.Q(('remaining_quantity__gte', 0)), name='inventory_supply_remaining_gte_zero'), models.CheckConstraint(condition=models.Q(('remaining_quantity__lte', models.F('quantity'))), name='inventory_supply_remaining_lte_quantity'), models.CheckConstraint(condition=models.Q(('unit_buy_price__gte', 0)), name='inventory_supply_unit_buy_price_gte_zero')],
            },
        ),
    ]
