# Generated by Django 5.2.15 on 2026-08-26 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorysupply'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySupplyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('shipment', 'Shipment'), ('customs', 'Customs'), ('insurance', 'Insurance'), ('tax', 'Tax'), ('commission', 'Commission'), ('handling', 'Handling'), ('storage', 'Storage'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='inventory.inventorysupply')),
            ],
            options={
                'db_table': 'inventory_supply_cost',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='inventory_supply_cost_amount_gte_zero')],
            },
        ),
    ]
