# Generated by Django 5.2.15 on 2026-08-26 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventorysupplycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysupply',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serializedstock',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serialized_stocks', to='inventory.inventorysupply'),
        ),
    ]
