# Generated by Django 5.2.15 on 2026-08-26 11:45

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventorysupply_received_at_serializedstock_supply'),
        ('order', '0013_order_shipping_original_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySupplyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=17)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_consumptions', to='order.orderitem')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.inventorysupply')),
            ],
            options={
                'db_table': 'inventory_supply_consumption',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_supply_consumption_qty_gt_zero'), models.CheckConstraint(condition=models.Q(('total_cost', django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_cost')))), name='inventory_supply_consumption_total_matches'), models.UniqueConstraint(fields=('order_item', 'supply'), name='inventory_supply_consumption_order_supply_unique')],
            },
        ),
    ]
