# Generated by Django 5.2.15 on 2026-08-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorysupplyconsumption'),
        ('order', '0013_order_shipping_original_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysupplyconsumption',
            name='reversed_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='inventorysupplyconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('reversed_quantity__gte', 0)), name='inventory_supply_consumption_reversed_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='inventorysupplyconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('reversed_quantity__lte', models.F('quantity'))), name='inventory_supply_consumption_reversed_lte_quantity'),
        ),
    ]
