# Generated by Django 5.2.15 on 2026-08-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_brand_categories'),
        ('inventory', '0011_inventorysupplyconsumption_reversed_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_profit_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cost_strategy', models.CharField(choices=[('latest', 'Latest'), ('weighted_average', 'Weighted average'), ('fifo_next', 'FIFO next')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='catalog.productvariants')),
            ],
            options={
                'db_table': 'inventory_variant_pricing',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('expected_profit_percentage__gte', 0)), name='inventory_variant_pricing_profit_gte_zero')],
            },
        ),
    ]
