# Generated by Django 5.2.15 on 2026-08-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_brand_categories'),
        ('inventory', '0012_variantpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=17)),
                ('cost_strategy', models.CharField(choices=[('latest', 'Latest'), ('weighted_average', 'Weighted average'), ('fifo_next', 'FIFO next')], max_length=20)),
                ('expected_profit_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(choices=[('inventory_pricing', 'Inventory pricing'), ('manual', 'Manual')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='catalog.productvariants')),
            ],
            options={
                'db_table': 'inventory_variant_price_history',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('old_price__gte', 0)), name='inventory_price_history_old_price_gte_zero'), models.CheckConstraint(condition=models.Q(('new_price__gte', 0)), name='inventory_price_history_new_price_gte_zero'), models.CheckConstraint(condition=models.Q(('cost_basis__gte', 0)), name='inventory_price_history_cost_basis_gte_zero'), models.CheckConstraint(condition=models.Q(('expected_profit_percentage__gte', 0)), name='inventory_price_history_profit_gte_zero')],
            },
        ),
    ]
