# Generated by Django 5.2.15 on 2026-09-06 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessprofile_dark_logo_and_more'),
        ('inventory', '0013_variantpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='business.businessprofile'),
        ),
    ]
