# Generated by Django 5.2.15 on 2026-09-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_warehouse_business'),
        ('marketplace', '0005_migrate_profit_config_to_business_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariantPricing',
        ),
    ]
