# Generated by Django 5.2.15 on 2026-09-10 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessprofile_dark_logo_and_more'),
        ('catalog', '0022_remove_inventory_strategy_fk'),
        ('inventory', '0015_remove_variant_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sellable', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('min_stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='business.businessprofile')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='catalog.productvariants')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_inventory',
                'indexes': [models.Index(fields=['variant', 'warehouse'], name='inv_variant_wh_idx'), models.Index(fields=['business'], name='inv_business_idx'), models.Index(fields=['warehouse'], name='inv_warehouse_idx')],
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'variant'), name='inventory_warehouse_variant_unique'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_quantity_gte_zero'), models.CheckConstraint(condition=models.Q(('sellable__gte', 0)), name='inventory_sellable_gte_zero'), models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='inventory_reserved_gte_zero'), models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('sellable'))), name='inventory_reserved_lte_sellable'), models.CheckConstraint(condition=models.Q(('sellable__lte', models.F('quantity'))), name='inventory_sellable_lte_quantity')],
            },
        ),
    ]
