# Generated by Django 5.2.15 on 2026-09-10 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_add_inventory_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('in_stock', 'In stock'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='in_stock', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.inventory')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.inventorysupply')),
            ],
            options={
                'db_table': 'inventory_unit',
                'indexes': [models.Index(fields=['inventory', 'state'], name='invunit_inventory_state_idx'), models.Index(fields=['state'], name='invunit_state_idx'), models.Index(fields=['supply'], name='invunit_supply_idx'), models.Index(fields=['created_at'], name='invunit_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('supply__isnull', False)), fields=('inventory', 'supply'), name='inventory_unit_inventory_supply_unique')],
            },
        ),
    ]
