# Generated by Django 5.2.15 on 2026-09-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessprofile_dark_logo_and_more'),
        ('inventory', '0017_inventoryunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Datetime')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_attribute_definitions', to='business.businessprofile')),
            ],
            options={
                'db_table': 'inventory_attribute_definition',
                'ordering': ['business', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='inventory.inventory')),
                ('attribute_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_attributes', to='inventory.inventoryattributedefinition')),
            ],
            options={
                'db_table': 'inventory_attribute',
            },
        ),
        migrations.CreateModel(
            name='InventoryUnitAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('attribute_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_attributes', to='inventory.inventoryattributedefinition')),
                ('inventory_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='inventory.inventoryunit')),
            ],
            options={
                'db_table': 'inventory_unit_attribute',
            },
        ),
        migrations.AddIndex(
            model_name='inventoryattributedefinition',
            index=models.Index(fields=['business'], name='invattrdef_business_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryattributedefinition',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='inventory_attrdef_business_code_unique'),
        ),
        migrations.AddIndex(
            model_name='inventoryattribute',
            index=models.Index(fields=['inventory'], name='invattr_inventory_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryattribute',
            index=models.Index(fields=['attribute_definition'], name='invattr_def_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryattribute',
            constraint=models.UniqueConstraint(fields=('inventory', 'attribute_definition'), name='inventory_attr_inventory_def_unique'),
        ),
        migrations.AddIndex(
            model_name='inventoryunitattribute',
            index=models.Index(fields=['inventory_unit'], name='invunitattr_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryunitattribute',
            index=models.Index(fields=['attribute_definition'], name='invunitattr_def_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryunitattribute',
            constraint=models.UniqueConstraint(fields=('inventory_unit', 'attribute_definition'), name='invunitattr_unit_def_unique'),
        ),
    ]
