# Generated by Django 5.2.15 on 2026-09-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_inventoryattributedefinition_inventoryattribute_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryunit',
            name='inventory_unit_inventory_supply_unique',
        ),
    ]
