# Generated by Django 5.2.15 on 2026-09-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_inventoryunit_inventory_unit_inventory_supply_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='inventory_reserved_lte_sellable',
        ),
    ]
