# Generated by Django 5.2.15 on 2026-09-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_remove_inventory_strategy_fk'),
        ('inventory', '0020_remove_inventory_inventory_reserved_lte_sellable'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='inventory.inventory')),
                ('source_inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='inventory.inventory')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transfers', to='catalog.productvariants')),
            ],
            options={
                'db_table': 'inventory_transfer',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['source_inventory'], name='invtransfer_source_idx'), models.Index(fields=['destination_inventory'], name='invtransfer_dest_idx'), models.Index(fields=['variant'], name='invtransfer_variant_idx'), models.Index(fields=['created_at'], name='invtransfer_created_idx')],
            },
        ),
    ]
