# Generated by Django 5.2.15 on 2026-09-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_businesscategory'),
        ('inventory', '0022_migrate_inventory_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysupply',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='business.businessprofile'),
        ),
    ]
