# Generated by Django 5.2.15 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_update_warehouse_default_constraint"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inventorysupply",
            index=models.Index(
                fields=["business", "variant", "supplied_at"],
                name="inv_supply_business_variant_at",
            ),
        ),
    ]
