# Generated by Django 5.2.15 on 2026-09-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_legacy_inventory_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'permissions': [('adjust_stock', 'Can adjust stock')]},
        ),
    ]
