# Generated by Django 5.2.15 on 2026-09-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_inventoryunit_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryunit',
            name='state',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('frozen', 'Frozen'), ('changed_type', 'Changed type')], default='in_stock', max_length=20),
        ),
    ]
