# Generated by Django 5.2.15 on 2026-09-30 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_businesscategory'),
        ('inventory', '0030_alter_inventoryunit_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryattributedefinition',
            options={'ordering': [models.OrderBy(models.F('business'), nulls_first=True), 'name']},
        ),
        migrations.AddField(
            model_name='inventoryattributedefinition',
            name='fa_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryattributedefinition',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_attribute_definitions', to='business.businessprofile'),
        ),
        migrations.AddConstraint(
            model_name='inventoryattributedefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('business__isnull', True)), fields=('code',), name='inventory_attrdef_global_code_unique'),
        ),
    ]
