# Generated by Django 5.2.15 on 2026-10-05 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_inventoryattributedefinition_options_and_more'),
        ('marketplace', '0009_seed_marketplace_payment_index'),
        ('order', '0015_remove_inventory_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysupplyconsumption',
            name='marketplace_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_consumptions', to='marketplace.marketplaceorderitem'),
        ),
        migrations.AlterField(
            model_name='inventorysupplyconsumption',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_consumptions', to='order.orderitem'),
        ),
        migrations.AddConstraint(
            model_name='inventorysupplyconsumption',
            constraint=models.UniqueConstraint(fields=('marketplace_order_item', 'supply'), name='inventory_supply_consumption_mkt_supply_unique'),
        ),
        migrations.AddConstraint(
            model_name='inventorysupplyconsumption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('marketplace_order_item__isnull', True), ('order_item__isnull', False)), models.Q(('marketplace_order_item__isnull', False), ('order_item__isnull', True)), _connector='OR'), name='inventory_supply_consumption_one_target'),
        ),
    ]
