# Generated by Django 5.2.15 on 2026-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='fa_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='fa_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='state',
            name='fa_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
