# Generated by Django 5.2.15 on 2026-10-01 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_businesscategory'),
        ('content', '0003_landingpage_cache_ttl_page_cache_ttl'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='business.businessprofile'),
        ),
        migrations.AddField(
            model_name='page',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_pages', to='business.businessprofile'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
        migrations.AddConstraint(
            model_name='landingpage',
            constraint=models.UniqueConstraint(fields=('business', 'slug'), name='content_landing_page_business_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='landingpage',
            constraint=models.UniqueConstraint(condition=models.Q(('business__isnull', True)), fields=('slug',), name='content_landing_page_global_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('business', 'slug'), name='content_page_business_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(condition=models.Q(('business__isnull', True)), fields=('slug',), name='content_page_global_slug_unique'),
        ),
    ]
