# Generated by Django 5.2.15 on 2026-10-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_landingpage_business_page_business_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='landingpage',
            name='content_landing_page_business_slug_unique',
        ),
        migrations.RemoveConstraint(
            model_name='landingpage',
            name='content_landing_page_global_slug_unique',
        ),
        migrations.RemoveConstraint(
            model_name='page',
            name='content_page_business_slug_unique',
        ),
        migrations.RemoveConstraint(
            model_name='page',
            name='content_page_global_slug_unique',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='business',
        ),
        migrations.RemoveField(
            model_name='page',
            name='business',
        ),
        migrations.AddConstraint(
            model_name='landingpage',
            constraint=models.UniqueConstraint(fields=('slug',), name='content_landing_page_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('slug',), name='content_page_slug_unique'),
        ),
    ]
