# Generated by Django 5.2.15 on 2026-08-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0015_variant_option_info'),
        ('customer', '0004_normalize_customer_phones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='catalog.product')),
            ],
            options={
                'db_table': 'wishlist',
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='wishlist_customer_created_idx'), models.Index(fields=['product'], name='wishlist_product_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'product'), name='wishlist_customer_product_unique')],
            },
        ),
    ]
