# Generated by Django 5.2.15 on 2026-10-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField(blank=True, default='')),
                ('required', models.BooleanField(default=False)),
                ('activate', models.BooleanField(default=True)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('component_lists', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_content_suggestion_page',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='business_content_suggestion_page_slug_unique')],
            },
        ),
    ]
