"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlsplit

from django.core.exceptions import ImproperlyConfigured
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


load_dotenv(BASE_DIR / ".env")


def env_bool(name, default):
    value = os.getenv(name)
    if value is None:
        return default
    if value.lower() in {"true", "1", "yes"}:
        return True
    if value.lower() in {"false", "0", "no"}:
        return False
    raise ImproperlyConfigured(f"{name} must be a boolean value")


SECRET_KEY = "django-insecure-!=d12q8564!7u^hd1%lbg6x0+xa!)kup$r(z3@f!w9&0@qlrn4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "domains.notifications.apps.NotificationsConfig",
    "domains.files.apps.FilesConfig",
    "domains.catalog.apps.CatalogConfig",
    "domains.inventory.apps.InventoryConfig",
    "domains.location.apps.LocationConfig",
    "domains.customer.apps.CustomerConfig",
    "core",
    "domains.users",
]

CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    f"redis://{os.getenv('REDIS_HOST', 'localhost')}:{os.getenv('REDIS_PORT', '6379')}/1",
)
CELERY_TASK_IGNORE_RESULT = True
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
NOTIFICATIONS_ALLOW_FAKE_SMS = env_bool("NOTIFICATIONS_ALLOW_FAKE_SMS", False)
CONFIRMED_REQUEST_DEV_CODE = os.getenv("CONFIRMED_REQUEST_DEV_CODE", "")
CONFIRMED_REQUEST_DEV_MODE = env_bool("CONFIRMED_REQUEST_DEV_MODE", False)
if CONFIRMED_REQUEST_DEV_CODE and not CONFIRMED_REQUEST_DEV_MODE:
    raise ImproperlyConfigured(
        "CONFIRMED_REQUEST_DEV_CODE requires CONFIRMED_REQUEST_DEV_MODE=True"
    )

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
    "confirmed_requests": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv(
            "CONFIRMED_REQUEST_REDIS_URL",
            f"redis://{os.getenv('REDIS_HOST', 'localhost')}:{os.getenv('REDIS_PORT', '6379')}/2",
        ),
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        "KEY_PREFIX": "uzshop",
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "core.middleware.language.HeaderLanguageMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fa"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
FILE_STORAGE_ALIASES = [
    alias.strip()
    for alias in os.getenv("FILE_STORAGE_ALIASES", "default").split(",")
    if alias.strip()
]
FILE_MAX_UPLOAD_SIZE = 20 * 1024 * 1024

STORAGE_BACKEND = os.getenv(
    "STORAGE_BACKEND", "django.core.files.storage.FileSystemStorage"
)
STORAGES = {
    "default": {"BACKEND": STORAGE_BACKEND},
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
    },
}

if STORAGE_BACKEND == "storages.backends.s3.S3Storage":
    storage_public_url = os.getenv("STORAGE_PUBLIC_URL", "")
    parsed_public_url = urlsplit(storage_public_url)
    if parsed_public_url.scheme not in {"http", "https"} or not parsed_public_url.netloc:
        raise ImproperlyConfigured(
            "STORAGE_PUBLIC_URL must be an absolute HTTP or HTTPS URL"
        )

    storage_options = {
        "access_key": os.getenv("STORAGE_ACCESS_KEY_ID"),
        "secret_key": os.getenv("STORAGE_SECRET_ACCESS_KEY"),
        "bucket_name": os.getenv("STORAGE_BUCKET_NAME"),
        "endpoint_url": os.getenv("STORAGE_ENDPOINT_URL"),
        "region_name": os.getenv("STORAGE_REGION_NAME"),
        "addressing_style": os.getenv("STORAGE_ADDRESSING_STYLE"),
        "signature_version": "s3v4",
        "default_acl": None,
        "querystring_auth": env_bool("STORAGE_QUERYSTRING_AUTH", False),
        "file_overwrite": env_bool("STORAGE_FILE_OVERWRITE", False),
        "custom_domain": (
            f"{parsed_public_url.netloc}{parsed_public_url.path.rstrip('/')}"
        ),
        "url_protocol": f"{parsed_public_url.scheme}:",
    }
    if not storage_options["bucket_name"]:
        raise ImproperlyConfigured("STORAGE_BUCKET_NAME is required for S3 storage")

    STORAGES["default"]["OPTIONS"] = {
        key: value for key, value in storage_options.items() if value is not None
    }
    MEDIA_URL = f"{storage_public_url.rstrip('/')}/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "domains.customer.auth.CustomerJWTAuthentication",
        "domains.users.auth.AdminJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "CHECK_REVOKE_TOKEN": True,
}

LANGUAGES = [("en", _("English")), ("fa", _("Persian"))]
LOCALE_PATHS = [
    BASE_DIR / "locale",
]
