from .customer import CustomerRegisterSerializer, CustomerLoginSerializer, CustomerProfileSerializer, CustomerUpdateSerializer, CustomerPreferenceSerializer
from .address import CustomerAddressSerializer
