# Generated by Django 5.2.1 on 2026-07-29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="FileStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={"db_table": "files_file_status", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("storage_alias", models.CharField(default="default", max_length=50)),
                ("object_key", models.CharField(max_length=500)),
                ("original_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=20)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("extension", models.CharField(blank=True, max_length=50)),
                ("size", models.PositiveBigIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_files", to=settings.AUTH_USER_MODEL)),
                ("status", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="files", to="files.filestatus")),
            ],
            options={
                "db_table": "files_file",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="files_status_created_idx"),
                    models.Index(fields=["file_type", "created_at"], name="files_type_created_idx"),
                    models.Index(fields=["checksum"], name="files_checksum_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("storage_alias", "object_key"), name="files_unique_storage_object")],
            },
        ),
    ]
