# Generated by Django 5.2.15 on 2026-08-21 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=40)),
                ('extension', models.CharField(blank=True, max_length=16)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'business_phone',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('platform', models.CharField(max_length=80)),
                ('url', models.URLField(max_length=500)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'business_social_link',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('availability_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('temporarily_unavailable', 'Temporarily unavailable'), ('maintenance', 'Maintenance'), ('holiday', 'Holiday')], default='open', max_length=32)),
                ('availability_message', models.CharField(blank=True, max_length=500)),
                ('availability_until', models.DateTimeField(blank=True, null=True)),
                ('cache_ttl', models.PositiveIntegerField(default=3600)),
            ],
            options={
                'db_table': 'business_profile',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='business_profile_singleton_id')],
            },
        ),
        migrations.CreateModel(
            name='BusinessWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('is_open', models.BooleanField(default=False)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('second_opens_at', models.TimeField(blank=True, null=True)),
                ('second_closes_at', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'business_working_day',
                'ordering': ['weekday'],
                'constraints': [models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='business_working_day_weekday_range'), models.CheckConstraint(condition=models.Q(models.Q(('second_closes_at__isnull', True), ('second_opens_at__isnull', True)), models.Q(('second_closes_at__isnull', False), ('second_opens_at__isnull', False)), _connector='OR'), name='business_working_day_second_pair')],
            },
        ),
    ]
