# Generated by Django 5.2.15 on 2026-09-06 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businesssociallink_logo_file'),
        ('files', '0002_file_statuses'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='dark_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_dark_logos', to='files.file'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='enamad_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='light_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_light_logos', to='files.file'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profiles', to='vendor.vendor'),
        ),
    ]
