# Generated by Django 5.2.15 on 2026-09-13 05:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessprofile_dark_logo_and_more'),
        ('files', '0002_file_statuses'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businessprofile',
            name='business_profile_singleton_id',
        ),
        migrations.AddField(
            model_name='businessphone',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_phones', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='businesssociallink',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_social_links', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='businessworkingday',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_working_days', to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='businessphone',
            name='key',
            field=models.SlugField(max_length=80),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='businesssociallink',
            name='key',
            field=models.SlugField(max_length=80),
        ),
        migrations.AlterField(
            model_name='businessworkingday',
            name='weekday',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddConstraint(
            model_name='businessphone',
            constraint=models.UniqueConstraint(fields=('vendor', 'key'), name='business_phone_vendor_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='businessprofile',
            constraint=models.UniqueConstraint(fields=('vendor',), name='business_profile_one_per_vendor'),
        ),
        migrations.AddConstraint(
            model_name='businesssociallink',
            constraint=models.UniqueConstraint(fields=('vendor', 'key'), name='business_social_link_vendor_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='businessworkingday',
            constraint=models.UniqueConstraint(fields=('vendor', 'weekday'), name='business_working_day_vendor_weekday_unique'),
        ),
    ]
