# Generated by Django 5.2.15 on 2026-09-13 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_remove_businessprofile_business_profile_singleton_id_and_more'),
        ('files', '0002_file_statuses'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businessphone',
            name='business_phone_vendor_key_unique',
        ),
        migrations.RemoveConstraint(
            model_name='businesssociallink',
            name='business_social_link_vendor_key_unique',
        ),
        migrations.RemoveField(
            model_name='businessphone',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='businesssociallink',
            name='vendor',
        ),
        migrations.AddField(
            model_name='businessphone',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='business.businessprofile'),
        ),
        migrations.AddField(
            model_name='businesssociallink',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='business.businessprofile'),
        ),
        migrations.AddConstraint(
            model_name='businessphone',
            constraint=models.UniqueConstraint(fields=('business', 'key'), name='business_phone_business_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='businesssociallink',
            constraint=models.UniqueConstraint(fields=('business', 'key'), name='business_social_link_business_key_unique'),
        ),
    ]
