# Generated by Django 5.2.15 on 2026-09-15 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_remove_businesssociallink_platform_logo_file'),
        ('catalog', '0022_remove_inventory_strategy_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='business.businessprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_categories', to='catalog.category')),
            ],
            options={
                'db_table': 'business_category',
                'constraints': [models.UniqueConstraint(fields=('business', 'category'), name='business_category_unique')],
            },
        ),
    ]
