# Generated by Django 5.2.15 on 2026-09-09 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0003_businessprofile_dark_logo_and_more'),
        ('catalog', '0020_productvariants_domain_productvariants_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='business.businessprofile')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_offers', to='catalog.productvariants')),
            ],
            options={
                'db_table': 'marketplace_business_offer',
                'constraints': [models.UniqueConstraint(fields=('business', 'variant'), name='marketplace_offer_business_variant_unique')],
            },
        ),
    ]
