# Generated by Django 5.2.15 on 2026-09-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessprofile_dark_logo_and_more'),
        ('catalog', '0021_remove_selling_fields'),
        ('marketplace', '0003_migrate_pricing_to_business_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessoffer',
            name='cost_strategy',
            field=models.CharField(choices=[('latest', 'Latest'), ('weighted_average', 'Weighted average'), ('fifo_next', 'FIFO next')], default='latest', max_length=20),
        ),
        migrations.AddField(
            model_name='businessoffer',
            name='expected_profit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddConstraint(
            model_name='businessoffer',
            constraint=models.CheckConstraint(condition=models.Q(('expected_profit_percentage__gte', 0)), name='marketplace_offer_profit_gte_zero'),
        ),
    ]
