# Generated by Django 5.2.15 on 2026-09-26 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_businesscategory'),
        ('catalog', '0023_add_vendor_creation_fields'),
        ('marketplace', '0005_migrate_profit_config_to_business_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('old_discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20, null=True)),
                ('new_discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20, null=True)),
                ('old_discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_strategy', models.CharField(choices=[('latest', 'Latest'), ('weighted_average', 'Weighted average'), ('fifo_next', 'FIFO next')], default='latest', max_length=20)),
                ('expected_profit_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('source', models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor')], default='admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_price_history', to='business.businessprofile')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='marketplace.businessoffer')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_price_history', to='catalog.productvariants')),
            ],
            options={
                'db_table': 'marketplace_offer_price_history',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['variant', 'created_at'], name='oph_variant_created_idx'), models.Index(fields=['business', 'created_at'], name='oph_business_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('old_price__gte', 0)), name='marketplace_offer_history_old_price_gte_zero'), models.CheckConstraint(condition=models.Q(('new_price__gte', 0)), name='marketplace_offer_history_new_price_gte_zero')],
            },
        ),
    ]
