# Generated by Django 5.2.15 on 2026-10-05 09:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_businesscategory'),
        ('business_payments', '0008_businesspaymentchannel_bank'),
        ('catalog', '0024_add_variant_ownership_fields'),
        ('customer', '0004_normalize_customer_phones'),
        ('files', '0002_file_statuses'),
        ('inventory', '0031_alter_inventoryattributedefinition_options_and_more'),
        ('marketplace', '0007_pricingstrategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fa_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'marketplace_order_status',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_cart', to='customer.customer')),
            ],
            options={
                'db_table': 'marketplace_cart',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_info', models.JSONField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('shipping_original_amount', models.DecimalField(decimal_places=2, default=Decimal('200000.00'), max_digits=15)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reservation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_orders', to='business.businessprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_orders', to='customer.customer')),
            ],
            options={
                'db_table': 'marketplace_order',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_type', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variant_info', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marketplace_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_order_items', to='marketplace.businessoffer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.marketplaceorder')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_order_items', to='catalog.productvariants')),
            ],
            options={
                'db_table': 'marketplace_order_item',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrderItemReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_order_reservations', to='inventory.inventory')),
                ('linked_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_order_reservations', to='inventory.inventoryunit')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='marketplace.marketplaceorderitem')),
            ],
            options={
                'db_table': 'marketplace_order_item_reservation',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ref_number', models.CharField(blank=True, max_length=128, null=True)),
                ('resource_account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_order_payments', to='business.businessprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='marketplace.marketplaceorder')),
                ('payment_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_payments', to='business_payments.businesspaymentchannel')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_payments', to='business_payments.businesspaymentmethod')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_order_payments', to='business_payments.businesspaymentstatus')),
            ],
            options={
                'db_table': 'marketplace_order_payment',
            },
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='successful_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_order', to='marketplace.marketplaceorderpayment'),
        ),
        migrations.CreateModel(
            name='MarketplaceOrderAction',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('fa_name', models.CharField(max_length=100)),
                ('admin', models.BooleanField(default=False)),
                ('customer', models.BooleanField(default=False)),
                ('set_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result_actions', to='marketplace.marketplaceorderstatus')),
            ],
            options={
                'db_table': 'marketplace_order_action',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='marketplace.marketplaceorderstatus'),
        ),
        migrations.CreateModel(
            name='MarketplaceOrderStatusAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_assignments', to='marketplace.marketplaceorderaction')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_actions', to='marketplace.marketplaceorderstatus')),
            ],
            options={
                'db_table': 'marketplace_order_status_actions',
                'ordering': ['order_status_id', 'order_action_id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplacePaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_payment_documents', to='files.file')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='marketplace.marketplaceorderpayment')),
            ],
            options={
                'db_table': 'marketplace_payment_document',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=16)),
                ('reason', models.TextField()),
                ('customer_note', models.TextField(blank=True, null=True)),
                ('refund_destination_type', models.CharField(choices=[('card', 'Card'), ('account', 'Account')], max_length=16)),
                ('refund_destination_value', models.CharField(max_length=64)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('customer_response', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_return_requests', to='customer.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='marketplace.marketplaceorder')),
            ],
            options={
                'db_table': 'marketplace_return_request',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceReturnRequestEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_return_request_evidence', to='files.file')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='marketplace.marketplacereturnrequest')),
            ],
            options={
                'db_table': 'marketplace_return_request_evidence',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_request_items', to='marketplace.marketplaceorderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.marketplacereturnrequest')),
            ],
            options={
                'db_table': 'marketplace_return_request_item',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.marketplacecart')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_cart_items', to='catalog.productvariants')),
            ],
            options={
                'db_table': 'marketplace_cart_item',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='marketplace_cart_item_quantity_positive'), models.UniqueConstraint(fields=('cart', 'variant'), name='marketplace_cart_item_cart_variant_unique')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('user_model', models.CharField(blank=True, max_length=100, null=True)),
                ('before_values', models.JSONField(default=dict)),
                ('after_values', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='marketplace.marketplaceorderaction')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='marketplace.marketplaceorder')),
            ],
            options={
                'db_table': 'marketplace_order_history',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='mkt_ord_hist_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceorderitem',
            index=models.Index(fields=['order'], name='mkt_ord_item_order_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorderitem',
            index=models.Index(fields=['marketplace_offer'], name='mkt_ord_item_offer_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='marketplace_order_item_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorderitemreservation',
            index=models.Index(fields=['linked_inventory'], name='mkt_ord_resrv_invtry_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorderitemreservation',
            index=models.Index(fields=['linked_unit'], name='mkt_ord_resrv_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorderpayment',
            index=models.Index(fields=['order'], name='mkt_ord_payment_order_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorderpayment',
            index=models.Index(fields=['business'], name='mkt_ord_payment_bus_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorderpayment',
            index=models.Index(fields=['business', 'order', 'status'], name='mkt_ord_pay_bus_ord_st_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceorderpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='marketplace_order_payment_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorder',
            index=models.Index(fields=['customer', '-created_at'], name='mkt_ord_customer_creat_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorder',
            index=models.Index(fields=['business', '-created_at'], name='mkt_ord_business_creat_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorder',
            index=models.Index(fields=['status', 'reservation_expires_at'], name='mkt_ord_status_resrv_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceorderstatusaction',
            constraint=models.UniqueConstraint(fields=('order_status', 'order_action'), name='marketplace_order_status_action_unique'),
        ),
        migrations.AddConstraint(
            model_name='marketplacepaymentdocument',
            constraint=models.UniqueConstraint(fields=('payment', 'file'), name='marketplace_payment_document_unique'),
        ),
        migrations.AddIndex(
            model_name='marketplacereturnrequest',
            index=models.Index(fields=['customer', '-requested_at'], name='mkt_ret_customer_req_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacereturnrequest',
            index=models.Index(fields=['order', 'status'], name='mkt_ret_order_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketplacereturnrequestevidence',
            constraint=models.UniqueConstraint(fields=('return_request', 'position'), name='marketplace_return_unique_evidence_position'),
        ),
        migrations.AddIndex(
            model_name='marketplacereturnrequestitem',
            index=models.Index(fields=['order_item'], name='mkt_ret_item_order_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketplacereturnrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='marketplace_return_item_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='marketplacereturnrequestitem',
            constraint=models.UniqueConstraint(fields=('return_request', 'order_item'), name='marketplace_return_unique_order_item'),
        ),
    ]
