# Generated by Django 5.2.15 on 2026-09-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_businesscategory'),
        ('business_payments', '0001_initial'),
        ('order', '0014_orderitemreservation_linked_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'business payment statuses',
                'db_table': 'business_payment_status',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='businesspayment',
            name='bp_payment_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='businesspayment',
            name='bp_payment_one_successful_per_order',
        ),
        migrations.AlterField(
            model_name='businesspayment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='business_payments.businesspaymentstatus'),
        ),
        migrations.AddIndex(
            model_name='businesspayment',
            index=models.Index(fields=['business', 'order', 'status'], name='bp_bus_order_st_idx'),
        ),
    ]
