# Generated by Django 5.2.15 on 2026-09-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_payments', '0003_seed_statuses_and_add_unique_index'),
        ('files', '0002_file_statuses'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businesspaymentchannel',
            name='bpc_business_code_unique',
        ),
        migrations.RemoveField(
            model_name='businesspaymentchannel',
            name='business',
        ),
        migrations.AddConstraint(
            model_name='businesspaymentchannel',
            constraint=models.UniqueConstraint(fields=('code',), name='bpc_code_unique'),
        ),
    ]
