# Generated by Django 5.2.15 on 2026-09-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_payments', '0004_remove_businesspaymentchannel_bpc_business_code_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businesspaymentmethod',
            name='bpm_business_code_unique',
        ),
        migrations.RemoveField(
            model_name='businesspaymentmethod',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businesspaymentmethod',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='businesspaymentmethod',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='businesspaymentmethod',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
