# Generated by Django 5.2.15 on 2026-09-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_payments', '0005_remove_method_business_created_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspaymentmethod',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
