# Generated by Django 5.2.15 on 2026-09-23 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('business_payments', '0007_restore_channel_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspaymentchannel',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_payment_channels', to='banks.bank'),
        ),
    ]
