# Generated by Django 5.2.15 on 2026-09-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='code',
            new_name='fa_name',
        ),
    ]
