# Generated by Django 5.2.15 on 2026-09-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_rename_code_bank_fa_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='fa_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
