# Generated by Django 5.2.15 on 2026-06-14 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('options', models.CharField(max_length=100)),
                ('filterable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalog_category_detail',
            },
        ),
        migrations.CreateModel(
            name='CategoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'catalog_category_status',
            },
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'catalog_product_status',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=250, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='catalog.categorystatus')),
            ],
            options={
                'db_table': 'catalog_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_products', to='catalog.category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_products', to='catalog.productstatus')),
            ],
            options={
                'db_table': 'catalog_product',
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=250)),
                ('extra_value', models.CharField(blank=True, max_length=250, null=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.categorydetail')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details_product', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_product_details',
            },
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inventory_strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorystrategy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_product_variants',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=250)),
                ('extra_value', models.CharField(blank=True, max_length=250, null=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.categorydetail')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.productvariants')),
            ],
            options={
                'db_table': 'catalog_product_variants_details',
            },
        ),
        migrations.CreateModel(
            name='CategoryDetailRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=512)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.categorydetail')),
            ],
            options={
                'db_table': 'catalog_category_detail_relation',
                'unique_together': {('category', 'detail')},
            },
        ),
    ]
