# Generated by Django 5.2.15 on 2026-07-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('assign_details_to_category', 'Can assign details to category')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('add_detail_to_product', 'Can add product details'), ('add_variant_to_product', 'Can add product variants')]},
        ),
    ]
