# Generated by Django 5.2.15 on 2026-07-28 19:07

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


def delete_legacy_variants(apps, schema_editor):
    # Development-only reset: variant details cascade before the variant rows disappear.
    apps.get_model("catalog", "ProductVariants").objects.all().delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('catalog', '0008_variant_detail_parent_cascade'),
        ('inventory', '0004_ensure_normal_inventory_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'catalog_category_variant_attribute',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'catalog_product_variant_selection',
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'catalog_variant_attribute',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku_code', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'catalog_variant_option',
                'ordering': ['attribute__name', 'name', 'id'],
            },
        ),
        migrations.RunPython(delete_legacy_variants, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='productvariantsdetails',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='productvariantsdetails',
            name='variant',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('assign_details_to_category', 'Can assign details to category'), ('assign_variant_attributes_to_category', 'Can assign variant attributes to category')]},
        ),
        migrations.AddField(
            model_name='productvariants',
            name='combination_key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='sku',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='productvariants',
            constraint=models.UniqueConstraint(fields=('product', 'combination_key'), name='catalog_product_variant_combination_unique'),
        ),
        migrations.AddField(
            model_name='categoryvariantattribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attribute_assignments', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='productvariantselection',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='catalog.productvariants'),
        ),
        migrations.AddConstraint(
            model_name='variantattribute',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='catalog_variant_attribute_normalized_name_unique'),
        ),
        migrations.AddField(
            model_name='productvariantselection',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_selections', to='catalog.variantattribute'),
        ),
        migrations.AddField(
            model_name='categoryvariantattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='catalog.variantattribute'),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.variantattribute'),
        ),
        migrations.AddField(
            model_name='productvariantselection',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_selections', to='catalog.variantoption'),
        ),
        migrations.DeleteModel(
            name='ProductVariantsDetails',
        ),
        migrations.AddConstraint(
            model_name='categoryvariantattribute',
            constraint=models.UniqueConstraint(fields=('category', 'attribute'), name='catalog_category_variant_attribute_unique'),
        ),
        migrations.AddConstraint(
            model_name='variantoption',
            constraint=models.UniqueConstraint(models.F('attribute'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='catalog_variant_option_normalized_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='variantoption',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('sku_code'), name='catalog_variant_option_sku_code_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='productvariantselection',
            constraint=models.UniqueConstraint(fields=('variant', 'attribute'), name='catalog_variant_selection_attribute_unique'),
        ),
        migrations.AddConstraint(
            model_name='productvariantselection',
            constraint=models.UniqueConstraint(fields=('variant', 'option'), name='catalog_variant_selection_option_unique'),
        ),
    ]
