# Generated by Django 5.2.15 on 2026-07-29 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_categoryvariantattribute_productvariantselection_and_more'),
        ('files', '0002_file_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('gallery', 'Gallery'), ('thumbnail', 'Thumbnail'), ('video', 'Video'), ('document', 'Document')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_files', to='files.file')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_files', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_product_file',
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['product', 'role', 'position'], name='catalog_prod_file_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'file'), name='catalog_product_file_unique'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='catalog_product_file_one_primary')],
            },
        ),
    ]
