# Generated by Django 5.2.15 on 2026-08-05 21:06

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


def normalize_detail_options(apps, schema_editor):
    CategoryDetail = apps.get_model("catalog", "CategoryDetail")
    CategoryDetailOption = apps.get_model("catalog", "CategoryDetailOption")
    ProductDetails = apps.get_model("catalog", "ProductDetails")

    for detail in CategoryDetail.objects.exclude(options="").iterator():
        options = []
        seen = set()
        for raw_name in detail.options.split(","):
            name = raw_name.strip()
            key = name.casefold()
            if not name or key in seen:
                continue
            seen.add(key)
            options.append(CategoryDetailOption.objects.create(
                detail_id=detail.id,
                name=name,
                position=len(options),
            ))
        option_by_name = {option.name.casefold(): option.id for option in options}
        for value in ProductDetails.objects.filter(detail_id=detail.id).only("id", "value"):
            option_id = option_by_name.get(value.value.strip().casefold())
            if option_id:
                ProductDetails.objects.filter(pk=value.id).update(option_id=option_id)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_productfile'),
        ('inventory', '0006_inventory_permissions'),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'catalog_brand',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryDetailOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'catalog_category_detail_option',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='productvariants',
            index=models.Index(fields=['product', 'price'], name='catalog_variant_price_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='catalog_brand_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='catalog_brand_normalized_name_unique'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'category', 'id'], name='catalog_product_public_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='catalog_product_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='catalog_product_desc_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddField(
            model_name='categorydetailoption',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_options', to='catalog.categorydetail'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_values', to='catalog.categorydetailoption'),
        ),
        migrations.AddConstraint(
            model_name='categorydetailoption',
            constraint=models.UniqueConstraint(models.F('detail'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='catalog_category_detail_option_normalized_name_unique'),
        ),
        migrations.RunPython(normalize_detail_options, migrations.RunPython.noop),
    ]
