# Generated by Django 5.2.15 on 2026-08-06 11:42

from django.db import migrations, models
from django.db.models import F


def copy_product_categories(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    for product in Product.objects.exclude(category_id__isnull=True).iterator():
        product.categories.add(product.category_id)


def backfill_fa_names(apps, schema_editor):
    for model_name in ("Brand", "Category", "VariantOption"):
        model = apps.get_model("catalog", model_name)
        model.objects.filter(fa_name__isnull=True).update(fa_name=F("name"))


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_category_name_unique_per_parent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_product_public_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, db_table='catalog_product_categories', related_name='products', to='catalog.category'),
        ),
        migrations.RunPython(copy_product_categories, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='brand',
            name='fa_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='fa_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='fa_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(backfill_fa_names, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'id'], name='catalog_product_status_idx'),
        ),
    ]
