# Generated by Django 5.2.15 on 2026-08-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_fa_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantoption',
            name='info',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
