# Generated by Django 5.2.15 on 2026-08-31 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_brand_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'catalog_product_variant_status',
            },
        ),
        migrations.AddField(
            model_name='productvariants',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.productvariantstatus'),
        ),
    ]
