# Generated by Django 5.2.15 on 2026-09-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_add_variant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='json_description',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
