# Generated by Django 5.2.15 on 2026-09-06 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_product_json_description'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='vendor.vendor'),
        ),
    ]
