# Generated by Django 5.2.15 on 2026-09-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_productvariants_domain_productvariants_vendor'),
        ('marketplace', '0003_migrate_pricing_to_business_offer'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productvariants',
            name='catalog_variant_price_idx',
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='price',
        ),
    ]
