# Generated by Django 5.2.15 on 2026-09-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_remove_selling_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariants',
            name='inventory_strategy',
        ),
    ]
